### ISSUE TITLE
segmentation fault on ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [Bitcoin-LE/bitcoinle-core#3]
qt wallet starts fine. After closing this and miner start, it crashes when a block is being mined. Waiting for metronome works, but with mining, it throws this error and crashes.

Target Hash: 0000000ef2f60000000000000000000000000000000000000000000000000000
Incrementing extra nonce...
Segmentation fault (core dumped)

cpu: amd

**Comment by Bitcoin-LE** [comment]
Fixed: v0.15.2
